apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
description: Priority class for VMs which should not be preemtited.
metadata:
  name: vm-standard
  labels:
    kubevirt-manager.io/managed: "true"
    kubevirt-manager: "true"
preemptionPolicy: Never
value: 999999999

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
description: Priority class for VMs which are allowed to be preemtited.
metadata:
  name: vm-preemptible
  labels:
    kubevirt-manager.io/managed: "true"
    kubevirt-manager: "true"
preemptionPolicy: PreemptLowerPriority
value: 1000000